server:
  port: 8085
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/filter_test
    username: root
    password: ENC(8hD3Ns3Xz6FGoDR6/E1DPDi18Jvro/SBQ1O6BpzM6V8=)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
